.TH MYSTRLEN 3 "September 2025" "Version 0.4.1" "Library Functions Manual"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B int mystrlen(const char* s);
.SH DESCRIPTION
The
.B mystrlen()
function returns the number of characters in the string pointed to by
.I s ,
excluding the terminating null byte ('\0').
.SH AUTHOR
Muhammad Tayyab <tyb3122@email.com>
