.TH MYSTRCAT 3 "September 2025" "Version 0.4.1" "Library Functions Manual"
.SH NAME
mystrcat \- concatenate two strings
.SH SYNOPSIS
.B int mystrcat(char* dest, const char* src);
.SH DESCRIPTION
The
.B mystrcat()
function appends the string pointed to by
.I src
to the end of the string pointed to by
.I dest .
The destination buffer must be large enough to contain the resulting string.
.SH AUTHOR
Muhammad Tayyab <tyb3122@email.com>
