.TH CLIENT 1 "September 2025" "Version 0.4.1" "User Commands"
.SH NAME
client \- sample program that demonstrates custom string and file functions
.SH SYNOPSIS
.B client
.RI [ file ]
.SH DESCRIPTION
The
.B client
program is a driver that tests the functionality of the custom
string functions (mystrlen, mystrcpy, etc.) and file functions
(wordCount, mygrep).
.PP
If a filename is provided, the file functions will analyze that file.
.SH AUTHOR
Muhammad Tayyab tyb3122@gmail.com
